[env:esp32-s3]
platform = espressif32
board = m5stack-cores3
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.arduino.psram_type = opi
board_build.partitions = partitions_custom.csv
board_upload.flash_size = 8MB

lib_deps = 
    m5stack/M5Unified@^0.1.16
    lvgl/lvgl@^8.3.11
    https://github.com/micro-bitcoin/uBitcoin.git

build_flags = 
    -Iinclude
    -DLV_CONF_INCLUDE_SIMPLE=1
    -DLV_CONF_SUPPRESS_DEFINE_CHECK=1
    -DBOARD_HAS_PSRAM
