name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO
      run: |
        pip install platformio
        pio platform install espressif32
    
    - name: Build Firmware
      run: pio run
    
    - name: Copy files to docs
      run: |
        mkdir -p docs
        cp .pio/build/esp32-s3/bootloader.bin docs/
        cp .pio/build/esp32-s3/partitions.bin docs/partition-table.bin
        cp .pio/build/esp32-s3/firmware.bin docs/seedsigner-esp32s3.bin
        cp web/index.html docs/
        cp web/manifest.json docs/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
