name: Build and Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install PlatformIO
      run: |
        pip install platformio
        pio platform install espressif32 --with-package=framework-arduinoespressif32
    
    - name: Build
      run: pio run
    
    - name: Prepare web
      run: |
        mkdir web_deploy
        cp .pio/build/esp32-s3/bootloader.bin web_deploy/
        cp .pio/build/esp32-s3/partitions.bin web_deploy/partition-table.bin
        cp .pio/build/esp32-s3/firmware.bin web_deploy/seedsigner-esp32s3.bin
        cp web/* web_deploy/
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./web_deploy
